[workspace]
members = ["origa", "tokenizer", "origa_ui", "tauri"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["yurvon-screamo <yurvon@ya.ru>"]
license-file = "LICENSE"
repository = "https://github.com/yurvon-screamo/origa"
readme = "README.md"

[workspace.dependencies]
# System
tokio = { version = "1.48", features = ["rt", "macros", "time"] }
async-trait = "0.1"
futures = "0.3"
indicatif = "0.18"
base64 = "0.22"
toml = "0.9"
tempfile = "3.23"
serde_json = "1.0"
reqwest = { version = "0.12", default-features = false, features = ["json"] }
ordered-float = "5.1"
zip = "7.0"
rusqlite = { version = "0.38", features = ["bundled"] }
regex = "1.12"
libz-sys = "*"
flate2 = { version = "*", features = ["zlib"] }
imp = { version = "0.1" }

# Logging
tracing = "0.1"

# OpenAI
async-openai-wasm = { version = "0.31", features = [
    "embedding",
    "responses",
    "batch",
    "model",
    "chat-completion",
] }

# Domain
ulid = { version = "1.2", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["std", "clock", "serde"] }
rand = "0.9"
getrandom = { version = "0.3.4", features = ["wasm_js"] }

# Japan
rs-fsrs = "1.2"
lindera = { version = "1.4", features = ["embedded-unidic"] }

# Origa workspace crates
origa = { path = "./origa" }
tokenizer = { path = "./tokenizer" }

# Utility
lazy_static = "1.4"

# Testing
rstest = "0.26"

leptos = { version = "0.7.8", features = ["csr"] }
leptos_meta = { version = "0.7", features = ["csr"] }
leptos_router = { version = "0.7" }
leptos-use = "0.18"
thaw = { version = "0.4", features = ["csr"] }
icondata = "0.7"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
serde-wasm-bindgen = "0.6"
console_error_panic_hook = "0.1"

# Tauri
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
tauri-build = { version = "2", features = [] } # UI
