[application]
name = "origa"
default_platform = "web"
out_dir = "dist"
asset_dir = "assets"

[web.app]
title = "Origa"

[web.watcher]
reload_html = true
watch_path = ["origa", "origa_ui", "assets"]

[bundle]
identifier = "new.uwuwu.origa"
publisher = "yurvon_screamo"
