[package]
name = "origa_ui"
version.workspace = true
edition.workspace = true
authors.workspace = true
license-file.workspace = true
repository.workspace = true
readme.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
leptos.workspace = true
leptos-use.workspace = true
leptos_router.workspace = true
leptos_meta.workspace = true
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true
js-sys.workspace = true
serde.workspace = true
serde-wasm-bindgen.workspace = true
console_error_panic_hook.workspace = true
web-sys = { workspace = true, features = ["Node", "Element"] }
origa.workspace = true
ulid.workspace = true
