[package]
name = "origa_ui_source"
version.workspace = true
edition.workspace = true
authors.workspace = true
license-file.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
origa = { path = "../origa" }

leptos.workspace = true
leptos_meta.workspace = true
leptos_router.workspace = true
console_log.workspace = true
log.workspace = true
console_error_panic_hook.workspace = true
thaw.workspace = true

[dev-dependencies]
wasm-bindgen.workspace = true
wasm-bindgen-test.workspace = true
web-sys.workspace = true
