[package]
name = "origa_ui_source"
version.workspace = true
edition.workspace = true
authors.workspace = true
license-file.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
leptos.workspace = true
leptos_router.workspace = true
thaw.workspace = true
icondata.workspace = true
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true
js-sys.workspace = true
serde-wasm-bindgen.workspace = true
serde.workspace = true
serde_json.workspace = true
console_error_panic_hook.workspace = true

# leptos-use = { workspace = true } # Temporarily commented due to compatibility issues
