[package]
name = "origa"
version.workspace = true
edition.workspace = true

[dependencies]

# System
tokio.workspace = true
async-trait.workspace = true
futures.workspace = true
indicatif.workspace = true
base64.workspace = true
toml.workspace = true
tempfile.workspace = true
serde_json.workspace = true
reqwest.workspace = true
ordered-float.workspace = true
zip.workspace = true
rusqlite.workspace = true
regex.workspace = true
libz-sys.workspace = true
flate2.workspace = true
rand.workspace = true
getrandom = { version = "0.2.16", features = ["js"] }

# Logging
tracing.workspace = true

# OpenAI
async-openai-wasm.workspace = true

# Domain
ulid.workspace = true
serde.workspace = true
chrono.workspace = true

# Japan
rs-fsrs.workspace = true
lindera.workspace = true

[dev-dependencies]
rstest.workspace = true

[target.wasm32-unknown-unknown]
rustflags = ['--cfg', 'getrandom_backend="wasm_js"']
